# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
linter:
  rules:
    # Enable additional rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    unnecessary_new: true
    unnecessary_const: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_if_null_operators: true
    unnecessary_null_checks: true
    prefer_null_aware_operators: true
    avoid_returning_null_for_void: true
    unnecessary_statements: true
    prefer_expression_function_bodies: true
    sort_child_properties_last: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_types_as_parameter_names: true
    camel_case_types: true
    non_constant_identifier_names: false
    constant_identifier_names: true
    library_names: true
    file_names: true
    library_prefixes: true
    avoid_empty_else: true
    control_flow_in_finally: true
    empty_statements: true
    unnecessary_brace_in_string_interps: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    unnecessary_lambdas: true
    avoid_function_literals_in_foreach_calls: true
    avoid_renaming_method_parameters: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_null_checks_in_equality_operators: true
    prefer_generic_function_type_aliases: true
    avoid_private_typedef_functions: true
    prefer_iterable_whereType: true
    unnecessary_getters_setters: true
    unnecessary_this: true
    prefer_initializing_formals: true
    type_init_formals: true
    empty_constructor_bodies: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_as: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    use_rethrow_when_possible: true
    use_to_and_as_if_applicable: true
    use_string_buffers: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    only_throw_errors: true
    prefer_constructors_over_static_methods: true
    prefer_mixin: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_multiple_declarations_per_line: true
    prefer_bool_in_asserts: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    void_checks: true